### ISSUE TITLE
Error while running "make"

### ISSUE THREAD

**Issue by ram1123** [vbfnlo/vbfnlo#1]
Dear VBFNLO authors,

I am trying to install vbfnlo.  I am installing it using following commands

 
    git clone git@github.com:vbfnlo/vbfnlo.git
    cd vbfnlo
    autoreconf -vi  #(only needed for git checkouts)
    ./configure  --with-root=/cvmfs/cms.cern.ch/slc6_amd64_gcc530/lcg/root/6.08.07/
    make -j 8
    make install

It working fine on my laptop and I am able to generate events using this. But, I tried the same step on the lxplus cluster (CERN cluster) and there I am getting an error while step "make". You can see the full log here [1].

Please let me know how I can fix this.

Thanks in advance for your support.

with regards,
Ram

P.S.: I also sent an email to "vbfnlo@itp.kit.edu". I was confused where to sent so sending a message to both places. So, please ignore the double message.

[1] [VBFinstall.txt](https://github.com/vbfnlo/vbfnlo/files/1135111/VBFinstall.txt)

**Comment by ram1123** [comment]
Thanks Michael for the answer.

For completeness I am writing my mistakes here and close this issue.

1. Mistake 1: replace `make -j 8`  with `make`

2. Mistake 2: At cluster we don't have administrative permission se we need to set path of installation.

       ./configure --with-root=/cvmfs/cms.cern.ch/slc6_amd64_gcc530/lcg/root/6.08.07/ --prefix=/afs/cern.ch/user/r/rasharma/work/aQGC_Studies/MC_SampleGeneration/CMSSW_9_3_0_pre1/src/VBFNLO_install/vbfnlo_install/

3. If doing `./configure` again then we have to do `make clean` first.

**Comment by michael-rauch** [comment]
For the record some further explanation to the first problem:  
To compile the loop functions, where the error occurred, gfortran needs a significant amount of memory. If you run out of it, this can lead to the seen behavior. Obviously, the more jobs you run in parallel, the less memory you have for each job. Otherwise, from the VBFNLO side using parallel make is supported.
